config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products
  resources :users, only: %i[index]
  resources :orders
end

app/models/application_record.rb
# frozen_string_literal: true

# アプリケーションレコード
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# frozen_string_literal: true

# 注文
class Order < ApplicationRecord
  has_many :details, class_name: 'OrderDetail', validate: true, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true
end

app/models/order_detail.rb
# frozen_string_literal: true

# 注文明細
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item, class_name: 'Product'
end

app/models/product.rb
# frozen_string_literal: true

# 製品
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :end_of_production, inclusion: { in: [true, false] }
end

app/models/user.rb
# frozen_string_literal: true

# ユーザー
class User < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :email, uniqueness: true
  validates_with EmailAddress::ActiveRecordValidator, field: :email

  validates :name, presence: true, length: { minimum: 3 }
  validates :address, length: { minimum: 10 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# アプリケーションコントローラ
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# 注文コントローラー
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show destroy]

  def index
    @orders = Order.includes(:user, details: :item).all
  end

  def show; end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: t('.create_successfully') }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @order.destroy
    format.html { redirect_to orders_url, notice: t('.destroy_successfully') }
  end

  private

  def set_order
    @order = Order.includes(details: :item).find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id, order_details_attributes: %i[id _destroy item quantity])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# 商品マスタメンテナンス
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t('.create_successfully') }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: t('.update_successfully') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: t('.destroy_successfully') }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ユーザーコントローラ
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# アプリケーションヘルパー
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_order_detail_fields.html.slim
tr.nested-fields
  td = f.text_field :item
  td = f.text_field :quantity
  td = link_to_remove_association t('.remove_row'), f

app/views/orders/index.html.slim
h1 = t('.h1')

table
  thead
    tr
      th = Order.human_attribute_name 'user.name'
      th = OrderDetail.model_name.human
      th.text-right = Order.human_attribute_name :sum

  tbody
    - @orders.each do |order|
      tr
        td = order.user.name
        td
          table
            thead
              tr
                th = OrderDetail.human_attribute_name 'product.name'
                th = OrderDetail.human_attribute_name :quantity
                th = OrderDetail.human_attribute_name 'product.price'
                th = OrderDetail.human_attribute_name :sum
            tbody
              - order.details.each do |detail|
                tr
                  td = detail.item.name
                  td.text-right = detail.quantity
                  td.text-right = detail.item.price
                  td.text-right = number_with_delimiter(detail.sum)
        td.text-right = number_with_delimiter(order.sum)

= link_to t('.goto_order'), new_order_path

app/views/orders/new.html.slim
h1 = t('.h1')

= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = t('.error', count: @order.errors.count)
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  table
    tbody
      tr
        th = f.label :user_id
        td = f.collection_select :user_id, User.all, :id, :name

  div.details
    = link_to_add_association t('.add_row'), f, :details
      table
        = f.fields_for :details do |d|
          = render 'order_detail_fields', f: d

  div.actions
    = f.submit

app/views/orders/show.html.slim
h1 = t('.h1')

table
  tr
    th = Order.human_attribute_name 'user.name'
    td = @order.user.name

  tr
    th = Order.human_attribute_name :details
    td
      table
        tr
          th = OrderDetail.human_attribute_name 'product.name'
          th = OrderDetail.human_attribute_name :quantity
          th = OrderDetail.human_attribute_name 'product.price'
          th = OrderDetail.human_attribute_name :sum
        tr
          - @order.details.each do |detail|
            tr
              td = detail.item.name
              td.text-right = detail.quantity
              td.text-right = detail.item.price
              td.text-right = number_with_delimiter(detail.sum)

= link_to t('.back'), orders_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = t('.error', count: @product.errors.count)
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .actions = f.submit class: 'btn-primary'

app/views/products/edit.html.slim
h1 = t('.h1')

== render 'form'

=> link_to t('.show'), @product
'|
=< link_to t('.back'), products_path

app/views/products/index.html.slim
h1 = t('.h1')

table
  thead
    tr
      th = Product.human_attribute_name :name
      th = Product.human_attribute_name :price
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.price
        td = link_to t('.show'), product
        td = link_to t('.edit'), edit_product_path(product)
        td = link_to t('.destroy'), product, data: { confirm: t('.destroy_confirm') }, method: :delete

br

= link_to t('.new_product'), new_product_path

app/views/products/new.html.slim
h1 = t('.h1')

== render 'form'

= link_to t('.back'), products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong
    = Product.human_attribute_name :name
    | :
  = @product.name
p
  strong
    = Product.human_attribute_name :price
    | :
  = @product.price

=> link_to t('.edit'), edit_product_path(@product)
'|
=< link_to t('.back'), products_path

app/views/users/index.html.slim
h1 = t('.h1')

table
  tr
    th = User.human_attribute_name :email
    th = User.human_attribute_name :name
    th = User.human_attribute_name :address

  - @users.each do |user|
    tr
      td = user.email
      td = user.name
      td = user.address